name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
    # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    # see https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test
