name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
    # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    # see https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test

  web-build-and-deploy:
    runs-on: ubuntu-latest
    name: web-build-and-deploy
    # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
    # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    # see https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build:web
      - name: Setup git user
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      # see https://www.npmjs.com/package/gh-pages
      - name: Deploy with gh-pages
        # see https://docs.github.com/en/actions/learn-github-actions/environment-variables#about-environment-variables
        # see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm run deploy:web -- -u "github-actions-bot <support+actions@github.com>"
